# -*- coding: utf-8 -*-
"""Flam_assign.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sD6YuRKSiKGWUdR8yxFQLIBFxv71UX5U
"""

# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import minimize
from google.colab import files

# Upload CSV file
uploaded = files.upload()
filename = list(uploaded.keys())[0]
data = pd.read_csv(filename)

# Extract x, y
x_data = data['x'].values
y_data = data['y'].values

# Correct t scaling: uniformly sample t from 6 to 60
n_points = len(data)
t_data = np.linspace(6, 60, n_points)

# Parametric function
def param_curve(params, t):
    theta_deg, M, X = params
    theta = np.deg2rad(theta_deg)  # Convert degrees to radians
    x = t * np.cos(theta) - np.exp(M*np.abs(t)) * np.sin(0.3*t) * np.sin(theta) + X
    y = 42 + t * np.sin(theta) + np.exp(M*np.abs(t)) * np.sin(0.3*t) * np.cos(theta)
    return x, y

# L1 loss function
def l1_loss(params, t, x_true, y_true):
    x_pred, y_pred = param_curve(params, t)
    loss = np.sum(np.abs(x_pred - x_true) + np.abs(y_pred - y_true))
    return loss

# Initial guess and bounds
initial_guess = [25, 0, 50]  # theta_deg, M, X
bounds = [(0, 50), (-0.05, 0.05), (0, 100)]

# Optimize parameters using L-BFGS-B method
result = minimize(
    l1_loss,
    initial_guess,
    args=(t_data, x_data, y_data),
    bounds=bounds,
    method='L-BFGS-B',
    options={'maxiter': 10000}
)

theta_est, M_est, X_est = result.x

# Compute final L1 distance
final_loss = l1_loss([theta_est, M_est, X_est], t_data, x_data, y_data)

# Print results
print(f"Estimated θ (deg): {theta_est:.6f}")
print(f"Estimated M: {M_est:.6f}")
print(f"Estimated X: {X_est:.6f}")
print(f"Final L1 Distance: {final_loss:.6f}")

# Plot actual vs predicted curve
x_pred, y_pred = param_curve([theta_est, M_est, X_est], t_data)
plt.figure(figsize=(10,6))
plt.plot(x_data, y_data, 'ro', label='Actual Points')
plt.plot(x_pred, y_pred, 'b-', label='Fitted Curve')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Actual vs Fitted Parametric Curve')
plt.legend()
plt.grid(True)
plt.show()

# LaTeX-ready parametric curve
print("\nLaTeX-ready parametric curve:")
print(f"(t*cos({theta_est:.6f}) - exp({M_est:.6f}*abs(t))*sin(0.3*t)*sin({theta_est:.6f}) + {X_est:.6f}, "
      f"42 + t*sin({theta_est:.6f}) + exp({M_est:.6f}*abs(t))*sin(0.3*t)*cos({theta_est:.6f}))")